// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WkApi.Core.Data;

#nullable disable

namespace WkApi.Apps.Daylog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407182106_AddDaylogEventTypeDefinitions")]
    partial class AddDaylogEventTypeDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WkApi.Apps.Daylog.Entities.DaylogEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.ToTable("DaylogEvents", (string)null);
                });

            modelBuilder.Entity("WkApi.Apps.Daylog.Entities.DaylogEventTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TextColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DaylogEventTypeDefinitions", (string)null);
                });

            modelBuilder.Entity("WkApi.Apps.Health.Entities.WeightInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WeightInKilograms")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("WeightInfos");
                });

            modelBuilder.Entity("WkApi.Apps.LastTime.Entities.LtiItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("tracked_items", "lti");
                });

            modelBuilder.Entity("WkApi.Apps.LastTime.Entities.LtiItemEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ItemId", "OccurredAtUtc")
                        .IsUnique();

                    b.ToTable("item_events", "lti");
                });

            modelBuilder.Entity("WkApi.Apps.Daylog.Entities.DaylogEvent", b =>
                {
                    b.HasOne("WkApi.Apps.Daylog.Entities.DaylogEventTypeDefinition", "TypeDefinition")
                        .WithMany("Events")
                        .HasForeignKey("EventType")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeDefinition");
                });

            modelBuilder.Entity("WkApi.Apps.LastTime.Entities.LtiItemEvent", b =>
                {
                    b.HasOne("WkApi.Apps.LastTime.Entities.LtiItem", "Item")
                        .WithMany("Events")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WkApi.Apps.Daylog.Entities.DaylogEventTypeDefinition", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("WkApi.Apps.LastTime.Entities.LtiItem", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
