services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV}
    container_name: wk-server-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT}:${PORT}"