services:
  api:
    build:
      context: ./backend
    container_name: wk-api
    expose:
      - "8080"

  web:
    build:
      context: ./frontend/wk-frontend
    container_name: wk-web
    ports:
      - "80:80"
    depends_on:
      - api