// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WkApi.Core.Data;

#nullable disable

namespace WkApi.Apps.Health.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405180041_AddHealthWeights")]
    partial class AddHealthWeights
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WkApi.Apps.Health.Entities.WeightInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WeightInKilograms")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("WeightInfos");
                });

            modelBuilder.Entity("WkApi.Apps.LastTime.Entities.LtiItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("tracked_items", "lti");
                });

            modelBuilder.Entity("WkApi.Apps.LastTime.Entities.LtiItemEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ItemId", "OccurredAtUtc")
                        .IsUnique();

                    b.ToTable("item_events", "lti");
                });

            modelBuilder.Entity("WkApi.Apps.LastTime.Entities.LtiItemEvent", b =>
                {
                    b.HasOne("WkApi.Apps.LastTime.Entities.LtiItem", "Item")
                        .WithMany("Events")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WkApi.Apps.LastTime.Entities.LtiItem", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
